console.log("This is JavaScript");
console.log("I am learning JavaScript");
console.log("JavaScript is easy to learn");
console.log("I am practicing coding");
console.log("I like programming");
console.log("I am a computer science student");
console.log("Coding is interesting");
console.log("I am improving my skills");
console.log("JavaScript is a programming language");
console.log("I enjoy learning new things");
console.log("I practice JavaScript every day");
console.log("I want to become a developer");
console.log("Learning coding is useful");
console.log("I am interested in web development");
console.log("HTML is used to create webpages");
console.log("CSS is used to style webpages");
console.log("JavaScript makes webpages interactive");
console.log("I am working on my project");
console.log("I am becoming a better programmer");
console.log("Practice makes programming easier");